apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgres
  namespace: newsletter
spec:
  type: bindings.postgres
  version: v1
  metadata:
    - name: url
      value: "postgres://adminuser:adminpass@localhost:5433/newsletter?sslmode=disable"
    - name: table
      value: "subscriptions"
    - name: operations
      value: "exec,query"
  scope:
    - newsletter-admin
    - newsletter
    - consumer
    - newsletter
