apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  # You can unplug Redis and plug in another pubsub component
  # https://docs.dapr.io/reference/components-reference/supported-pubsub/
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      value: "localhost:6380"
    - name: topic
      value: "subscriptions"
