apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgres
  namespace: default
spec:
  type: bindings.postgres
  version: v1
  metadata:
    - name: url
      value: "postgres://citus:newsletterTest!@c-ytimocin-test-postgres.ru4ckrgdxgqwi5.postgres.cosmos.azure.com:5432/newsletter"
    - name: table
      value: "subscriptions"
    - name: operations
      value: "exec"
  scope:
    - newsletter-admin
    - newsletter
    - consumer
    - newsletter
