apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../../docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../../docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: newsletter
            - name: POSTGRES_PASSWORD
              value: adminpass
            - name: POSTGRES_USER
              value: adminuser
          image: postgres:latest
          name: newsletter-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
            - mountPath: /docker-entrypoint-initdb.d/init-db.sh
              name: postgres-cm1
              subPath: init-db.sh
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - configMap:
            items:
              - key: init-db.sh
                path: init-db.sh
            name: postgres-cm1
          name: postgres-cm1
