apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../../docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: registry
  name: registry
spec:
  ports:
    - name: "5055"
      port: 5055
      targetPort: 5000
  selector:
    io.kompose.service: registry
