apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../../docker-compose.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: s3
  name: s3
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: s3
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../../docker-compose.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: s3
    spec:
      containers:
        - env:
            - name: DEBUG
              value: "0"
          image: localstack/localstack:s3-latest
          name: localstack-s3
          ports:
            - containerPort: 4566
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      restartPolicy: Always
