apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: subscription
spec:
  topic: subscriptions
  # When there is a new message in the topic, Dapr will send a POST request to the following endpoint
  route: /dapr/subscribe
  pubsubname: pubsub
